# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1121, 711)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../res/Setup.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.CompressButton = CompressButton(self.centralwidget)
        self.CompressButton.setMinimumSize(QtCore.QSize(160, 160))
        self.CompressButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CompressButton.setText("")
        self.CompressButton.setObjectName("CompressButton")
        self.gridLayout.addWidget(self.CompressButton, 4, 0, 1, 1)
        self.CompressedText = CompressedText(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.CompressedText.setFont(font)
        self.CompressedText.setObjectName("CompressedText")
        self.gridLayout.addWidget(self.CompressedText, 4, 1, 3, 1)
        self.original_text = OriginalText(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_text.sizePolicy().hasHeightForWidth())
        self.original_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.original_text.setFont(font)
        self.original_text.setObjectName("original_text")
        self.gridLayout.addWidget(self.original_text, 0, 1, 4, 1)
        self.SwitchButton = SwitchButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SwitchButton.sizePolicy().hasHeightForWidth())
        self.SwitchButton.setSizePolicy(sizePolicy)
        self.SwitchButton.setMinimumSize(QtCore.QSize(146, 146))
        self.SwitchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SwitchButton.setText("")
        self.SwitchButton.setObjectName("SwitchButton")
        self.gridLayout.addWidget(self.SwitchButton, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 5, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "NLP Speech Compressor"))
        self.label.setText(_translate("MainWindow", "音频输入"))
        self.label_2.setText(_translate("MainWindow", "精简摘要"))
from Qt_CompressButton import CompressButton
from Qt_CompressedText import CompressedText
from Qt_OriginalText import OriginalText
from Qt_SwitchButton import SwitchButton


if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()

    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
